version: '3.8'

services: 
  web:
    build: .
    #command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn bookstore_project1.wsgi -b 0.0.0.0:8000
    environment: 
      - ENVIRONMENT=development
      - SECRET_KEY=aix1ly*hh8gl$$bi*%qf^x4-mums#%zmyy%b5-6nc@-s!j=cno7
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51IDe0fIw7padbDjWciDWOXNSxHw31WyWz8zWJFwJbfjFz0HXQ2tnZiFxccdW3zQdBRgTlVF90825udJw27qliF02001t8r22ct
      - STRIPE_TEST_SECRET_KEY=sk_test_51IDe0fIw7padbDjWbVJQW5VR8enkCgqrSZ2rVBPsm8Kfox0pFLCaJDzdndwzXrrvf6zmdwE7Hz2OMd6nnJ0MDOkz00HP8qnEt3 
    volumes: 
      - .:/code
    ports: 
      - 8000:8000
    depends_on: 
      - db
  db:
    image: postgres:13
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes: 
  postgres_data: